# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c49c6f0d490555b97c4ff076afbc71832f002a6c3909209e8eb97c0e3cf416f4eac143f47219f4bbc93affbf62e159f332fb2a3ac9f2133ad38b06e7b75221b1

test:
  secret_key_base: dbbae25915960d01c87ccd0b429c4f5111c328de7d05374e8df8b225a4efc2214b986add30ccc3840354de6aaf951c4589bef0a6a9cf1df9c6aca2d8c8621833

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
